language: python

cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache

matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
      env:
        - INCLUDE_SDIST=true

    - os: osx
      osx_image: xcode11.3
      language: generic

  allow_failures:
    - os: osx

deploy:
  provider: script
  script: python -m twine upload dist/*
  skip_cleanup: true
  on:
    tags: true
    condition: $INCLUDE_SDIST = true

before_install:
- python3 --version

install:
- python3 -m pip install --upgrade -r requirements-setuptools.txt
- python3 -m pip install -r requirements.txt

# Qt libraries
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -q update && sudo apt-get -y install libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0; fi
# xvfb is only needed on linux
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python3 -m pip install -r requirements-xvfb.txt; fi

- python3 -m pip install -e .
- python3 -m pip install codecov
- python3 -m pip uninstall -y echoes_menu_mod_gui

script:
- python3 setup.py bdist_wheel
- python3 -m pip install --upgrade dist/*
- python3 -m pytest --cov echoes_menu_mod_gui
- if [[ "$INCLUDE_SDIST" == "true" ]]; then python3 setup.py sdist; fi
